[package]
name = "rustector_btc_5mn"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "Rustector_btc_5mn"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.24", features = ["rustls-tls-native-roots"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ratatui = "0.29"
crossterm = "0.28"
futures-util = "0.3"
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1"
ordered-float = "4"

[profile.release]
opt-level = 3
